### ISSUE TITLE
Migrate existing tests to `pytest` from `unittest`.

### ISSUE THREAD

**Issue by mrhappyasthma** [mrhappyasthma/IsThisStockGood#80]
Existing tests are not running as part of the github actions. I believe it's because I implemented them using `unittest` and we are now using `pytest` (which seems to be the preferred options from some googling).

**Comment by kocielnik** [comment]
Good note!

I actually should've included the line `python run_all_tests.py` in the new GitHub Actions config, because it _was_ there in the CircleCI config.

I don't think migrating to PyTest is _required_ to get these tests to work.

While it's not required, I do think it will unify the test logic.

Before we migrate to PyTest, we make sure some tests (not only "API" ones) run _at all_ for incoming PRs.

That was my goal in #81.

**Comment by kocielnik** [comment]
My, that was quick.

Thank you! :)
